[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Default settings for all functions
  timeout = 26
  memory = 1024

[build]
  publish = "."

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
