[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."ai-quiz"]
  timeout = 26
  memory = 1024

[build]
  publish = "."

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
